### ISSUE TITLE
types.h:324:40: error: unknown type name ‘time_t’

### ISSUE THREAD

**Issue by redblade7** [mikeyk730/Rogue-Collection#11]
I'm trying to compile the v3.0.4 source under Gentoo Linux and am unable to.

> make -C Rogomatic
> make[1]: Entering directory '(REMOVED)/Rogue-Collection-3.0.4/src/Rogomatic'
> gcc -c -o arms.o arms.c -w -shared -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -s -I../Shared -I../MyCurses -DROGUE_COLLECTION 
> In file included from arms.c:32:
> types.h:324:40: error: unknown type name ‘time_t’
>  typedef struct { int gamecnt, gamesum; time_t inittime; int timeswritten; } lrnrec;
>                                         ^~~~~~
> make[1]: *** [makefile:25: arms.o] Error 1
> make[1]: Leaving directory '(REMOVED)/Rogue-Collection-3.0.4/src/Rogomatic'
> make: *** [makefile:11: all] Error 2

Even though this seems like a simple fix, I am having problems later in the compilation process, so in case I'm wrong, I will let you handle this and then report the next bug if I continue to have problems.

**Comment by mikeyk730** [comment]
I'm doing my active development on Windows, so it's very possible I  broke the build for Linux. I don't really have a good strategy for this at the moment, but I will take a look

**Comment by mikeyk730** [comment]
I pushed some changes that fix the linux build

**Comment by mikeyk730** [comment]
Unfortunately the makefile in master builds an older (SDL) version of the program, which is a bit buggy and is lacking many features.  I need to create one for the new (QML) version

**Comment by mikeyk730** [comment]
With the latest master, the makefile builds the QML version.  It requires qmake to be in your path

**Comment by redblade7** [comment]
Builds successfully now, thank you!
