### ISSUE TITLE
Scores do not save for 5.4.2

### ISSUE THREAD

**Issue by Fixer-007** [mikeyk730/Rogue-Collection#3]
Rogue54.scr is at 0 bytes after several games. Not sure about other kinds. Windows 7, RC 2.2

**Comment by mikeyk730** [comment]
Fixed in the repo with https://github.com/mikeyk730/Rogue-Collection/commit/afebbdd4a6e6b65f2dc86f88494cd730a9c0188a

**Comment by mikeyk730** [comment]
Bugfix is included in 3.0 release
