### ISSUE TITLE
Unable to start, absent api-ms-win-core-winrt-l1-1-0.dll

### ISSUE THREAD

**Issue by Fixer-007** [mikeyk730/Rogue-Collection#8]
Happens on new 3.0.1 release. RRC 2.2 works fine, Windows 7 SP1 x64

**Comment by mikeyk730** [comment]
My guess here is that I built the latest release against a newer version of Qt. Let me see if I can build an older Qt version

**Comment by boweden** [comment]
I also have this problem, but I get a slightly different message.  "The application was unable to start correctly (0xc000007b). Click OK to close the application"

Do I need a specific version of C++ redistributable or .NET Framework or DirectX ? (the readme isn't clear on this).

Thanks

**Comment by mikeyk730** [comment]
@boweden are you able to run the 2.2 release?

**Comment by boweden** [comment]
hi,
yes 2.2 seems to work fine.  I suppose I'll stick with it for now.  Thank you

**Comment by mikeyk730** [comment]
I will try to get a new build of the v3.0 release in the next few days

**Comment by mikeyk730** [comment]
@Fixer-007 @boweden, try out the v3.0.2 release to see if it resolves the issue

**Comment by Fixer-007** [comment]
It works now!

**Comment by boweden** [comment]
Thanks, works for me as well.
