### ISSUE TITLE
"Rogue's name:" prompt screen does not show characters when typing

### ISSUE THREAD

**Issue by Fixer-007** [mikeyk730/Rogue-Collection#9]
RCC 3.0.2, win7, any game that asks your name

**Comment by mikeyk730** [comment]
Thanks for bringing this up. It looks like all user input that's supposed to go to the screen is broken. I'll get a fix soon

**Comment by mikeyk730** [comment]
Fixed with 92ab30c55060bd2c022840a35c87fc181fb3cabb, will be in the next release.

**Comment by mikeyk730** [comment]
In v3.0.3

**Comment by Fixer-007** [comment]
Fixed for me, ty
